services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      # This keeps rate-limiter database persistent even if the container is deleted
      - ./src:/app/src